apiVersion: v1
kind: Service
metadata:
  name: {{ include "spinwheel-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spinwheel-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "spinwheel-backend.selectorLabels" . | nindent 4 }}
