namespace: spinwheel

replicaCount: 1

image:
  repository: registry.k8s.blacktoaster.com/spinwheel-frontend
  pullPolicy: Always
  tag: "26d06a1"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    external-dns.alpha.kubernetes.io/target: "pi5.k8s.blacktoaster.com"
  host: spinwheel.k8s.blacktoaster.com
  tls:
    enabled: true
    secretName: spinwheel-frontend-tls

certificate:
  enabled: true
  issuerName: vault-issuer
  issuerKind: ClusterIssuer

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
