{{- if .Values.claude.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spinwheel-backend.fullname" . }}-claude
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "spinwheel-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.claude.apiKey }}
{{- end }}
